package com.example.hr_bot.entity.enums;

public enum PermissionEnum {

    //department company
    READ_SALARY_EMPLOYEE,
    ADD_MANAGER_TASK, ADD_EMPLOYEE_TASK,
    EMPLOYEE_CRUD, EMPLOYEE_ADD, EMPLOYEE_EDIT, EMPLOYEE_DELETE, EDIT_ONE_EMPLOYEE, EMPLOYEE_READ,
    COMPANY_CRUD, COMPANY_READ, COMPANY_EDIT, COMPANY_DELETE, COMPANY_ADD
}
